"""make meeting_id optional in tasks

Revision ID: 967b09385e84
Revises: 4fa848f658f6
Create Date: 2026-07-22 22:42:55.311097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '967b09385e84'
down_revision: Union[str, Sequence[str], None] = '4fa848f658f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'meeting_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'meeting_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
