"""add last_reminder_sent_at to tasks

Revision ID: a92792dfd452
Revises: 690dbc539c39
Create Date: 2026-09-03 22:15:24.083370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a92792dfd452'
down_revision: Union[str, Sequence[str], None] = '690dbc539c39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('last_reminder_sent_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'last_reminder_sent_at')
    # ### end Alembic commands ###
